apiVersion: v1
kind: Service
metadata:
    name: server-client-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: service #The selector should match the one that we defined in the deployment file for the different serversn
    ports: #We need to define the ports that this service is going to manage
        - port: 5000
          targetPort: 5000